[project]
name = "my-simple-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
[project.scripts]
my-simple-app = "my_simple_app:main"